struct Education {
    uuid: String, 
    name: String,
    education_type: Enum<EducationType>,
    institution: Organization,
    major: String,
    minor: String,
    area: String,
    degree_level: Enum<DegreeLevel>,
    degree_name: String,
    certification: String,
    start_date: Date,
    end_date: Date,
    description: String,
    achievements: Vec<Achievement>,
    extra_curriculars: Vec<ExtraCurricular>,
    gpa: String,
    personal_notes: Vec<String>,
}